/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "var(--primary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "surface-dim": "var(--surface-dim)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface": "var(--surface)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-tint": "var(--surface-tint)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-error": "var(--on-error)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-primary": "var(--on-primary)",
        "on-background": "var(--on-background)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container": "var(--surface-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-primary-container": "var(--on-primary-container)",
        "error": "var(--error)",
        "on-surface": "var(--on-surface)",
        "on-secondary": "var(--on-secondary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "secondary-container": "var(--secondary-container)",
        "secondary": "var(--secondary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "error-container": "var(--error-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "background": "var(--background)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "primary": "var(--primary)",
        "tertiary": "var(--tertiary)",
        "outline-variant": "var(--outline-variant)",
        "surface-container-highest": "var(--surface-container-highest)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "outline": "var(--outline)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-variant": "var(--surface-variant)",
        "primary-container": "var(--primary-container)"
      },
      borderRadius: {
        "none": "0",
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
